// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
  about: () =>
    import(
      /* webpackChunkName: "prismic__slices__about" */ "./About/index.vue"
    ),
  contact: () =>
    import(
      /* webpackChunkName: "prismic__slices__contact" */ "./Contact/index.vue"
    ),
  home: () =>
    import(/* webpackChunkName: "prismic__slices__home" */ "./Home/index.vue"),
  how_to_eat_ramen: () =>
    import(
      /* webpackChunkName: "prismic__slices__how_to_eat_ramen" */ "./HowToEatRamen/index.vue"
    ),
  menu: () =>
    import(/* webpackChunkName: "prismic__slices__menu" */ "./Menu/index.vue"),
 
};
